import datetime
import rrdtool
from os import uname

from settings import RRD_FILE, datadir


class rrdgraph:

    def __init__(self, width):
        self.date = datetime.datetime.now().strftime("%d/%m/%Y %H:%M")
        self.host = uname()[1]
        self.width = width

    def visitors(self, start, title):
        file = datadir + 'png/visitors' + start + '.png'
        rrdtool.graph(file, '-s' + start, '-w' + self.width, '-vOnline users',
                      '-texpreszo.nl/forum - ' + title,
                      '-WGenerated by ' + self.host + ' - ' + self.date, '-E',
                      "DEF:total=" + RRD_FILE + ":total:AVERAGE",
                      "DEF:registered=" + RRD_FILE + ":registered:AVERAGE",
                      "DEF:hidden=" + RRD_FILE + ":hidden:AVERAGE",
                      "DEF:chat=" + RRD_FILE + ":chat:AVERAGE",
                      "CDEF:members=registered,hidden,+",
                      "COMMENT: ",
                      "AREA:total#99ccff:Totaal",
                      "AREA:members#6699ff:Ingelogd",
                      "AREA:chat#2a4fa2:Chat",
                      "COMMENT: ")
        return open(file, "rb").read()

    def chat(self, start, title):
        file = datadir + 'png/chat' + start + '.png'
        rrdtool.graph(file, '-s' + start, '-w' + self.width, '-vOnline users',
                      '-texpreszo.nl/chat - ' + title,
                      '-WGenerated by ' + self.host + ' - ' + self.date,
                      '-E', '-Y',
                      "DEF:chat=" + RRD_FILE + ":chat:AVERAGE",
                      "COMMENT: ",
                      "AREA:chat#2a4fa2:Chat",
                      "COMMENT: ")
        return open(file, "rb").read()

<<<<<<< HEAD
	def posts(self, start, title):
		file = datadir + 'png/posts' + start + '.png'
		rrdtool.graph(file, '-s' + start, '-w' + self.width, '-vAantal', '-texpreszo.nl/forum - ' + title, '-WGenerated by ' + self.host + ' - ' + self.date, '-Y', '-l35000', '-r',
			"DEF:posts=" + RRD_FILE + ":posts:AVERAGE",
			"COMMENT: ",
			"AREA:posts#ff9900:Posts",
			"COMMENT: ")
		return open(file, "rb").read()
=======
    def posts(self, start, title):
        file = datadir + 'png/posts' + start + '.png'
        rrdtool.graph(file, '-s' + start, '-w' + self.width, '-vAantal',
                      '-texpreszo.nl/forum - ' + title,
                      '-WGenerated by ' + self.host + ' - ' + self.date,
                      '-Y', '-l50000', '-r',
                      "DEF:posts=" + RRD_FILE + ":posts:AVERAGE",
                      "COMMENT: ",
                      "AREA:posts#ff9900:Posts",
                      "COMMENT: ")
        return open(file, "rb").read()
>>>>>>> 587977e4a9bf2cb416a395cdbc6ec359f72994f9

    def members(self, start, title):
        file = datadir + 'png/members' + start + '.png'
        rrdtool.graph(file, '-s' + start, '-w' + self.width, '-vAantal',
                      '-texpreszo.nl/forum - ' + title,
                      '-WGenerated by ' + self.host + ' - ' + self.date,
                      '-l2000', '-r',
                      "DEF:members=" + RRD_FILE + ":members:AVERAGE",
                      "COMMENT: ",
                      "AREA:members#009900:Members",
                      "COMMENT: ")
        return open(file, "rb").read()

    def topics(self, start, title):
        file = datadir + 'png/topics' + start + '.png'
        rrdtool.graph(file, '-s' + start, '-w' + self.width, '-vAantal',
                      '-texpreszo.nl/forum - ' + title,
                      '-WGenerated by ' + self.host + ' - ' + self.date,
                      '-l900', '-r',
                      "DEF:topics=" + RRD_FILE + ":topics:AVERAGE",
                      "COMMENT: ",
                      "AREA:topics#ff1100:Topics",
                      "COMMENT: ")
        return open(file, "rb").read()

    def absolute_traffic():
        """
        alle waardes van de 5 minuten intervallen optellen en delen door het
        aantal intervalen dan krijg je per dag een getal en daar kun je dan
        weer een heel leuk grafiekje van maken, dat weergeeft of de gemiddelde
        drukte toeneemt of afneemt
        """
